#!/bin/bash

NAME="foodie"                                 # Name of the application
DJANGODIR=/home/amarnath/Desktop/My_projects/foodie     # Django project directory
SOCKFILE=localhost:8000   # we will communicte using this unix socket
USER=amarnath                             # the user to run as
GROUP=amarnath                            # the group to run as
NUM_WORKERS=3                             # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=foodie.settings    # which settings file should Django use
DJANGO_WSGI_MODULE=foodie.wsgi            # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
ps aux | grep gunicorn
cd /home/amarnath/Desktop/My_projects
source myenv/bin/activate
cd foodie
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH


# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves
#  (do not use --daemon)
exec /home/amarnath/Desktop/My_projects/myenv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
 -- name $NAME \
 -- workers $NUM_WORKERS \
 -- user=$USER --group=$GROUP \
 -- bind=$SOCKFILE \
 -- log-level=debug \
 -- log-file=-
