# Generated by Django 3.1.2 on 2020-11-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201116_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_item',
        ),
        migrations.AddField(
            model_name='order',
            name='food_item',
            field=models.ManyToManyField(to='home.FoodItem'),
        ),
    ]
