# Generated by Django 3.1.2 on 2020-11-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201118_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_item',
        ),
        migrations.AddField(
            model_name='order',
            name='food_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.fooditem'),
        ),
    ]
